#!/usr/bin/env python3
"""
Static page generator for Hero Squad.

Generates 6 pages x 3 languages = 18 HTML files from the templates below:
    ./           Russian  (lang="ru")
    ./tj/        Tajik    (lang="tg")
    ./en/        English  (lang="en")

Every visible string is written once as T("ru", "tj", "en").
Do NOT edit the generated *.html files by hand - edit this script and re-run:

    python tools/build_pages.py

admin.html is hand-written and is NOT generated by this script.
Bump ASSET_VERSION whenever CSS/JS changes so browsers (and GitHub Pages
cache) fetch the new files.
"""
import pathlib

ROOT_DIR = pathlib.Path(__file__).resolve().parents[1]
SITE = ROOT_DIR
ASSET_VERSION = "8"

ICONS = {
    "ig": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor"/></svg>',
    "tg": '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M21.5 4.3 2.9 11.5c-1.3.5-1.2 1.2-.2 1.5l4.7 1.5 1.8 5.6c.2.6.4.8.9.8.4 0 .6-.2.9-.5l2.3-2.2 4.7 3.5c.9.5 1.5.2 1.7-.8l3.1-14.6c.3-1.3-.5-1.9-1.3-1.5zM8.8 14l9.4-6-7.3 6.9-.3 3.2z"/></svg>',
    "wa": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 21l1.6-4.6A8.5 8.5 0 1 1 8 19.6z"/><path d="M9 9.5c0 3 2.5 5.5 5.5 5.5l1.2-1.4-2-1-1 .8a4 4 0 0 1-2-2l.8-1-1-2z" fill="currentColor" stroke="none"/></svg>',
    "yt": '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M22 8.2a3 3 0 0 0-2-2.1C18.2 5.6 12 5.6 12 5.6s-6.2 0-8 .5a3 3 0 0 0-2 2.1A31 31 0 0 0 1.6 12a31 31 0 0 0 .4 3.8 3 3 0 0 0 2 2.1c1.8.5 8 .5 8 .5s6.2 0 8-.5a3 3 0 0 0 2-2.1 31 31 0 0 0 .4-3.8 31 31 0 0 0-.4-3.8zM10 15V9l5.2 3z"/></svg>',
    "arrow": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><path d="M5 12h14M13 6l6 6-6 6"/></svg>',
    "left": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><path d="M15 6l-6 6 6 6"/></svg>',
    "right": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><path d="M9 6l6 6-6 6"/></svg>',
    "phone": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 1.9.7 2.8a2 2 0 0 1-.5 2.1L8 9.9a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.4c.9.3 1.8.6 2.8.7a2 2 0 0 1 1.7 2z"/></svg>',
    "mail": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="4" width="20" height="16" rx="3"/><path d="m22 7-10 6L2 7"/></svg>',
    "pin": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0z"/><circle cx="12" cy="10" r="3"/></svg>',
    "clock": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>',
    "mask": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 8c3-2 15-2 18 0 0 6-3 10-9 10S3 14 3 8z"/><path d="M7 10.5c1-.8 3-.8 3.5.5M17 10.5c-1-.8-3-.8-3.5.5"/></svg>',
    "calendar": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="18" rx="3"/><path d="M16 2v4M8 2v4M3 10h18"/></svg>',
    "car": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 17h14v-5l-2-5H7l-2 5z"/><circle cx="7.5" cy="17.5" r="1.5"/><circle cx="16.5" cy="17.5" r="1.5"/><path d="M5 12h14"/></svg>',
    "star": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m12 2 3 6.5 7 .9-5.1 4.8 1.3 7L12 17.8 5.8 21.2l1.3-7L2 9.4l7-.9z"/></svg>',
    "cake": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 21V11h16v10M2 21h20M4 15c2 1.5 4 1.5 6 0s4-1.5 6 0 4 1.5 4 0M12 4v4M12 4c-1 0-1.5-1-1-2"/></svg>',
    "map": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 3-6 3v15l6-3 6 3 6-3V3l-6 3z"/><path d="M9 3v15M15 6v15"/></svg>',
    "school": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 9l10-5 10 5-10 5z"/><path d="M6 11v5c3 2 9 2 12 0v-5"/></svg>',
    "camera": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 7h3l2-3h6l2 3h3a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1z"/><circle cx="12" cy="13" r="4"/></svg>',
    "sparkle": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2v6M12 16v6M2 12h6M16 12h6M5 5l3 3M16 16l3 3M19 5l-3 3M8 16l-3 3"/></svg>',
    "shield": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2 4 5v6c0 5 3.5 9.5 8 11 4.5-1.5 8-6 8-11V5z"/><path d="m9 12 2 2 4-4"/></svg>',
}

LOGO = """<svg class="logo-mark" viewBox="0 0 48 48" aria-hidden="true">
  <defs><linearGradient id="lg" x1="0" y1="0" x2="1" y2="1"><stop offset=".5" stop-color="#1d3ed6"/><stop offset=".5" stop-color="#e62429"/></linearGradient></defs>
  <path d="M24 2 43 12v24L24 46 5 36V12z" fill="url(#lg)" stroke="#fff" stroke-width="2"/>
  <path d="M27 9 15 27h8l-3 12 13-19h-8z" fill="#fff"/>
</svg>"""

GLOVE = """<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M14 44V24l-3-8c-.6-1.8 1.8-2.8 2.8-1.2L17 20V7c0-2 3-2 3 0v11-13c0-2 3-2 3 0v13-11c0-2 3-2 3 0v12-9c0-2 3-2 3 0v17c3-3 6-4 7-2s-4 6-6 10l-3 7z" fill="#c9a227" stroke="#f5c518" stroke-width="1.2"/><circle cx="24" cy="31" r="2.6" fill="#ff8a00"/></svg>"""
I = ICONS

LANGS = {"ru": ("", "ru"), "tj": ("tj/", "tg"), "en": ("en/", "en")}  # код: (папка, html lang)
L = "ru"


def T(ru, tj, en):
    return {"ru": ru, "tj": tj, "en": en}[L]


def R():
    return "" if L == "ru" else "../"


def lang_href(code, page):
    folder = LANGS[code][0]
    return R() + folder + page


ASCII_ART = r"""<!--
   _   _ _____ ____   ___    ____   ___  _   _    _    ____
  | | | | ____|  _ \ / _ \  / ___| / _ \| | | |  / \  |  _ \
  | |_| |  _| | |_) | | | | \___ \| | | | | | | / _ \ | | | |
  |  _  | |___|  _ <| |_| |  ___) | |_| | |_| |/ ___ \| |_| |
  |_| |_|_____|_| \_\\___/  |____/ \__\_\\___//_/   \_\____/
"""


def ascii_comment():
    return ASCII_ART + T(
        "\n  Привет, человек, который смотрит исходный код!\n  На сайте спрятано 16 секретов. Подсказка: нажми клавишу «ё» (или `).\n-->",
        "\n  Салом, касе ки коди сарчашмаро мебинад!\n  Дар сайт 16 сир пинҳон аст. Маслиҳат: тугмаи «ё» (ё `)-ро пахш кун.\n-->",
        "\n  Hi there, source-code reader!\n  16 secrets are hidden on this site. Hint: press the ` key.\n-->")


def nav_items():
    return [("index.html", "home", T("Главная", "Асосӣ", "Home")), ("heroes.html", "heroes", T("Герои", "Қаҳрамонон", "Heroes")),
            ("services.html", "services", T("Услуги", "Хизматҳо", "Services")), ("about.html", "about", T("О нас", "Дар бораи мо", "About")),
            ("contacts.html", "contacts", T("Контакты", "Тамос", "Contacts"))]


def tagline():
    return T("ГЕРОИ НА ПРАЗДНИК", "ҚАҲРАМОНОН БА ҶАШН", "HEROES FOR YOUR PARTY")


def head(title, desc, page, fname, loader=False, page_no="01"):
    nav = "".join(f'<a href="{h}" data-page="{p}">{t}</a>' for h, p, t in nav_items())
    sw = "".join(f'<a href="{lang_href(c, fname)}" data-lang="{c}" hreflang="{LANGS[c][1]}" class="{"on" if c == L else ""}">{c.upper()}</a>' for c in LANGS)
    ld = (f'<div class="loader" aria-hidden="true"><div class="loader-word">HERO SQUAD</div><div class="loader-sub">'
          f'{T("Костюмы надеты · герои в пути", "Либосҳо пӯшида шуд · қаҳрамонон дар роҳанд", "Suits on · heroes on the way")}</div></div>') if loader else ""
    alts = "".join(f'\n  <link rel="alternate" hreflang="{LANGS[c][1]}" href="{lang_href(c, fname)}">' for c in LANGS)
    return f"""<!DOCTYPE html>
{ascii_comment()}
<html lang="{LANGS[L][1]}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <meta name="description" content="{desc}">
  <meta name="theme-color" content="#07070b">{alts}
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 48 48'%3E%3Cpath d='M24 2 43 12v24L24 46 5 36V12z' fill='%23e62429'/%3E%3Cpath d='M27 9 15 27h8l-3 12 13-19h-8z' fill='%23fff'/%3E%3C/svg%3E">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Oswald:wght@400;500;600&family=Russo+One&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{R()}assets/css/style.css?v={ASSET_VERSION}">
  <link rel="stylesheet" href="{R()}assets/css/secrets.css?v={ASSET_VERSION}">
  <link rel="stylesheet" href="{R()}assets/css/guide.css?v={ASSET_VERSION}">
</head>
<body data-page="{page}" data-root="{R()}">
{ld}
<div class="progress"></div>

<header class="header">
  <div class="container">
    <a class="logo" href="index.html" aria-label="Hero Squad">{LOGO}<span>HERO SQUAD<small>{tagline()}</small></span></a>
    <nav class="nav" aria-label="{T('Основное меню', 'Менюи асосӣ', 'Main menu')}">{nav}<div class="lang-switch mobile-only">{sw}</div></nav>
    <div class="header-cta">
      <div class="lang-switch" aria-label="{T('Язык', 'Забон', 'Language')}">{sw}</div>
      <a class="btn" href="contacts.html#book">{T('Забронировать', 'Фармоиш', 'Book now')}</a>
      <button class="burger" aria-label="{T('Открыть меню', 'Кушодани меню', 'Open menu')}"><span></span><span></span><span></span></button>
    </div>
  </div>
</header>

<aside class="side-rail" aria-label="Social">
  <a href="#" aria-label="Instagram">{I['ig']}</a>
  <a href="#" aria-label="Telegram">{I['tg']}</a>
  <a href="#" aria-label="WhatsApp">{I['wa']}</a>
  <a href="#" aria-label="YouTube">{I['yt']}</a>
  <span class="line"><i></i></span>
  <span class="page-no">{page_no} / 05</span>
</aside>

<main>
"""


def foot():
    nav = "".join(f'<li><a href="{h}">{t}</a></li>' for h, p, t in nav_items())
    return f"""
</main>

<footer class="footer">
  <div class="container">
    <div class="footer-big">HERO SQUAD</div>
    <div class="footer-grid">
      <div>
        <a class="logo" href="index.html">{LOGO}<span>HERO SQUAD<small>{tagline()}</small></span></a>
        <p>{T('Аниматоры в костюмах любимых героев на дни рождения, выпускные и семейные праздники. Худжанд и Душанбе.',
              'Аниматорон дар либоси қаҳрамонони дӯстдошта барои зодрӯзҳо, хатмҳо ва ҷашнҳои оилавӣ. Хуҷанд ва Душанбе.',
              'Performers in your favourite heroes’ costumes for birthdays, graduations and family parties. Khujand & Dushanbe.')}</p>
        <div class="gauntlet" role="button" tabindex="0" aria-label="Infinity Gauntlet">
          {GLOVE}
          <div><b>{T('Перчатка', 'Дастпӯшак', 'Gauntlet')}</b><div class="slots"></div><small></small></div>
        </div>
      </div>
      <div>
        <h4>{T('Навигация', 'Саҳифаҳо', 'Navigation')}</h4>
        <ul>{nav}</ul>
      </div>
      <div>
        <h4>{T('Праздники', 'Ҷашнҳо', 'Parties')}</h4>
        <ul>
          <li><a href="services.html">{T('Дни рождения', 'Зодрӯзҳо', 'Birthdays')}</a></li>
          <li><a href="services.html">{T('Квесты со злодеем', 'Квест бо бадкирдор', 'Villain quests')}</a></li>
          <li><a href="services.html">{T('Выпускные', 'Ҷашни хатм', 'Graduations')}</a></li>
          <li><a href="services.html">{T('Академия героев', 'Академияи қаҳрамонон', 'Hero Academy')}</a></li>
        </ul>
      </div>
      <div>
        <h4>{T('Связь с базой', 'Тамос бо база', 'Contact HQ')}</h4>
        <ul>
          <li><a href="tel:+992927770000">+992 92 777 00 00</a></li>
          <li><a href="mailto:hello@herosquad.tj">hello@herosquad.tj</a></li>
          <li>{T('Ежедневно 9:00–21:00', 'Ҳар рӯз 9:00–21:00', 'Daily 9:00–21:00')}</li>
        </ul>
        <div style="display:flex;align-items:center;gap:12px;margin-top:18px">
          <button class="arc" aria-label="Arc reactor"></button>
          <small style="color:var(--muted)">{T('Не трогай реактор.', 'Ба реактор даст нарасон.', 'Don’t touch the reactor.')}</small>
        </div>
      </div>
    </div>
    <div class="footer-bottom">
      <span>© <span data-year></span> Hero Squad · {T('учебный проект по веб-дизайну. Не связан с Marvel и Disney.', 'лоиҳаи таълимӣ аз фанни веб-дизайн. Ба Marvel ва Disney алоқа надорад.', 'a web design student project. Not affiliated with Marvel or Disney.')}</span>
      <span>{T('Сделано с ♥ в Худжанде', 'Бо ♥ дар Хуҷанд сохта шуд', 'Made with ♥ in Khujand')} · <a href="404.html" style="color:inherit;opacity:.35">{T('мультивселенная', 'мултиолам', 'multiverse')}</a></span>
    </div>
  </div>
</footer>

<script src="{R()}assets/js/data.js?v={ASSET_VERSION}"></script>
<script src="{R()}assets/js/firebase-config.js?v={ASSET_VERSION}"></script>
<script src="{R()}assets/js/db.js?v={ASSET_VERSION}"></script>
<script src="{R()}assets/js/main.js?v={ASSET_VERSION}"></script>
<script src="{R()}assets/js/secrets.js?v={ASSET_VERSION}"></script>
<script src="{R()}assets/js/guide.js?v={ASSET_VERSION}"></script>
<script src="{R()}assets/js/live.js?v={ASSET_VERSION}"></script>
</body>
</html>
"""


def page_hero(eyebrow, title_html, lead, fig, bg, crumbs, vert):
    return f"""
<section class="page-hero" style="--ph:{bg}">
  <img class="fig" src="{R()}assets/img/{fig}" alt="">
  <div class="container">
    <div class="crumbs"><a href="index.html">{T('Главная', 'Асосӣ', 'Home')}</a> / <span>{crumbs}</span></div>
    <h1 class="title">{title_html}</h1>
    <p class="lead" style="color:rgba(255,255,255,.85)">{lead}</p>
    <span class="eyebrow" style="color:#fff">{eyebrow}</span>
  </div>
  <span class="vert-label">{vert}</span>
</section>
"""


# ======================= ГЛАВНАЯ =======================
def p_index():
    m1 = "".join(f"<span>{x}</span>" for x in [T("День рождения", "Зодрӯз", "Birthdays"), T("Квест со злодеем", "Квест бо бадкирдор", "Villain quest"), T("Выпускной", "Ҷашни хатм", "Graduation"), T("Академия героев", "Академияи қаҳрамонон", "Hero Academy"), T("Фотосессия", "Аксбардорӣ", "Photo shoot")]) * 4
    m2 = "".join(f"<span>{x}</span>" for x in [T("Мстители, общий сбор!", "Интиқомгирандагон, ҷамъ шавед!", "Avengers, assemble!"), T("Без скучных аниматоров", "Бе аниматорҳои дилгиркунанда", "No boring entertainers"), T("Кино-костюмы", "Либосҳои синамоӣ", "Movie-grade suits")]) * 5
    R_ = R()
    return head(T("Hero Squad — герои Marvel на детский праздник", "Hero Squad — қаҳрамонони Marvel ба ҷашни кӯдакон", "Hero Squad — Marvel heroes for kids’ parties"),
                T("Аниматоры в костюмах супергероев на дни рождения и детские праздники в Худжанде и Душанбе.", "Аниматорон дар либоси суперқаҳрамонон барои зодрӯз ва ҷашнҳои кӯдакона дар Хуҷанд ва Душанбе.", "Superhero-costumed performers for birthdays and kids’ parties in Khujand and Dushanbe."),
                "home", "index.html", loader=True, page_no="01") + f"""
<section class="hero" data-theme="spider">
  <div class="hero-bg"></div>
  <div class="container hero-grid">
    <div class="hero-text">
      <span class="eyebrow" style="color:#fff">{T('Детские праздники · Худжанд · Душанбе', 'Ҷашнҳои кӯдакона · Хуҷанд · Душанбе', 'Kids’ parties · Khujand · Dushanbe')}</span>
      <h1 class="hero-title">
        <span class="line"><span>{T('Герои', 'Қаҳрамонон', 'Heroes')}</span></span>
        <span class="line"><span class="hl">{T('на твой', 'ба ҷашни', 'for your')}</span></span>
        <span class="line"><span>{T('праздник', 'ту', 'party')}</span></span>
      </h1>
      <p class="hero-desc">{T('Человек-паук на дне рождения, Железный человек на выпускном, Доктор Дум, который похищает торт. Профессиональные аниматоры в кино-костюмах — праздник, который ребёнок запомнит навсегда.',
                             'Одам-тортанак дар зодрӯз, Одами оҳанин дар ҷашни хатм, Доктор Дум, ки тортро медуздад. Аниматорони касбӣ дар либосҳои синамоӣ — ҷашне, ки кӯдак онро ҳеҷ гоҳ фаромӯш намекунад.',
                             'Spider-Man at the birthday, Iron Man at the graduation, Doctor Doom stealing the cake. Professional performers in movie-grade suits — a party your child will never forget.')}</p>
      <div class="hero-actions">
        <a class="btn" href="services.html#calc">{T('Собрать праздник', 'Ҷашн созед', 'Build a party')} {I['arrow']}</a>
        <a class="btn ghost" href="heroes.html">{T('Смотреть героев', 'Қаҳрамононро бинед', 'Meet the heroes')}</a>
      </div>
    </div>
    <div class="hero-stage">
      <div class="hero-slide" data-theme="spider">
        <div class="poster-frame"></div>
        <div class="poster"><img src="{R_}assets/img/spiderman.jpg" alt="Spider-Man"></div>
        <span class="hero-name">01 · {T('Человек-паук', 'Одам-тортанак', 'Spider-Man')}</span>
      </div>
      <div class="hero-slide" data-theme="iron">
        <div class="poster-frame"></div>
        <div class="poster"><img src="{R_}assets/img/ironman.jpg" alt="Iron Man" style="object-position:50% 25%"></div>
        <span class="hero-name">02 · {T('Железный человек', 'Одами оҳанин', 'Iron Man')}</span>
      </div>
      <div class="hero-slide" data-theme="strange">
        <div class="poster-frame"></div>
        <div class="poster" style="--pbg:radial-gradient(circle at 50% 30%,#ffb347,#a8360c 45%,#1a0d2e)"></div>
        <img class="popout" src="{R_}assets/img/strange.png" alt="Doctor Strange">
        <span class="hero-name">03 · {T('Доктор Стрэндж', 'Доктор Стрэндж', 'Doctor Strange')}</span>
      </div>
      <div class="hero-slide" data-theme="panther">
        <div class="poster-frame"></div>
        <div class="poster" style="--pbg:radial-gradient(circle at 50% 30%,#a173ff,#3d1a8f 50%,#0b0418)"></div>
        <img class="popout" src="{R_}assets/img/panther.png" alt="Black Panther" style="height:96%">
        <span class="hero-name">04 · {T('Чёрная Пантера', 'Паланги Сиёҳ', 'Black Panther')}</span>
      </div>
      <button class="stone" data-stone="space" style="left:4%;bottom:2%" aria-label="?"></button>
    </div>
  </div>
  <div class="hero-controls">
    <div class="hero-count"><b>01</b><small> / 04</small></div>
    <button class="round-btn prev" aria-label="←">{I['left']}</button>
    <button class="round-btn next" aria-label="→">{I['right']}</button>
  </div>
  <div class="hero-bar"></div>
  <div class="scroll-hint">{T('листай', 'поён', 'scroll')}<i></i></div>
</section>

<div class="marquees"><div class="marquee"><div class="marquee-track">{m1}</div></div>
<div class="marquee alt"><div class="marquee-track">{m2}</div></div></div>

<section class="section">
  <div class="container">
    <div class="stats reveal">
      <div class="stat"><b><span data-count="1240">0</span><em>+</em></b><span>{T('праздников проведено', 'ҷашн гузаронида шуд', 'parties thrown')}</span></div>
      <div class="stat"><b><span data-count="8">0</span></b><span>{T('героев в команде', 'қаҳрамон дар даста', 'heroes on the team')}</span></div>
      <div class="stat"><b><span data-count="98">0</span><em>%</em></b><span>{T('детей кричат «ещё!»', 'кӯдакон «боз!» мегӯянд', 'of kids shout “again!”')}</span></div>
      <div class="stat"><b>∞</b><span>{T('улыбок и фото', 'табассум ва акс', 'smiles and photos')}</span></div>
    </div>
  </div>
</section>

<section class="section" style="padding-top:20px">
  <div class="container">
    <div class="section-head reveal">
      <span class="eyebrow">{T('Как это работает', 'Чӣ тавр кор мекунад', 'How it works')}</span>
      <h2 class="title">{T('Четыре шага <span class="red">до подвига</span>', 'Чор қадам <span class="red">то корнамоӣ</span>', 'Four steps <span class="red">to glory</span>')}</h2>
      <p class="lead">{T('Вы выбираете героя — мы делаем остальное: сценарий, реквизит, музыку и фото.', 'Шумо қаҳрамонро интихоб мекунед — боқиаш аз мо: сенария, реквизит, мусиқӣ ва акс.', 'You pick the hero — we handle the rest: script, props, music and photos.')}</p>
    </div>
    <div class="steps">
      <div class="step reveal" data-d="0"><span class="ico">{I['mask']}</span><h3>{T('Выберите героя', 'Қаҳрамонро интихоб кунед', 'Pick a hero')}</h3><p>{T('Один герой или целая команда Мстителей — под возраст и интересы ребёнка.', 'Як қаҳрамон ё тамоми дастаи Интиқомгирандагон — мувофиқи синну шавқи кӯдак.', 'One hero or the whole Avengers team — matched to your child’s age and interests.')}</p></div>
      <div class="step reveal" data-d="1"><span class="ico">{I['calendar']}</span><h3>{T('Назначьте дату', 'Санаро муайян кунед', 'Choose a date')}</h3><p>{T('Онлайн-заявка за 2 минуты. Перезвоним и согласуем сценарий.', 'Дархости онлайн дар 2 дақиқа. Занг зада, сенарияро мувофиқа мекунем.', 'Book online in 2 minutes. We’ll call back to agree on the script.')}</p></div>
      <div class="step reveal" data-d="2"><span class="ico">{I['car']}</span><h3>{T('Мы прилетаем', 'Мо парвоз карда меоем', 'We fly in')}</h3><p>{T('Дом, кафе, школа или парк — герои приезжают с реквизитом и музыкой.', 'Хона, қаҳвахона, мактаб ё боғ — қаҳрамонон бо реквизит ва мусиқӣ меоянд.', 'Home, café, school or park — heroes arrive with props and music.')}</p></div>
      <div class="step reveal" data-d="3"><span class="ico">{I['star']}</span><h3>{T('Эпичный праздник', 'Ҷашни афсонавӣ', 'An epic party')}</h3><p>{T('Игры, квест, посвящение в герои, фото и ни одной скучной минуты.', 'Бозиҳо, квест, қабул ба қаҳрамонон, акс ва ҳеҷ лаҳзаи дилгиркунанда.', 'Games, a quest, a hero initiation, photos and not a single boring minute.')}</p></div>
    </div>
  </div>
</section>

<section class="section" style="padding-top:20px">
  <div class="container">
    <div class="section-head reveal" style="display:flex;justify-content:space-between;align-items:flex-end;gap:20px;flex-wrap:wrap">
      <div><span class="eyebrow">{T('Команда', 'Даста', 'The team')}</span><h2 class="title">{T('Кого <span class="outline">позовём?</span>', 'Киро <span class="outline">даъват кунем?</span>', 'Who do <span class="outline">we call?</span>')}</h2></div>
      <a class="btn ghost" href="heroes.html">{T('Все 8 героев', 'Ҳамаи 8 қаҳрамон', 'All 8 heroes')} {I['arrow']}</a>
    </div>
    <div class="heroes-row" id="heroes-preview"></div>
  </div>
</section>

<section class="banner">
  <div class="bg" data-parallax style="background-image:url({R_}assets/img/ironman.jpg);background-position:50% 12%"></div>
  <div class="container reveal">
    <span class="eyebrow" style="color:var(--gold)">{T('Наша философия', 'Фалсафаи мо', 'Our philosophy')}</span>
    <p class="quote">{T('Каждый ребёнок — <em>супергерой.</em> Мы просто приносим костюмы.', 'Ҳар кӯдак — <em>суперқаҳрамон</em> аст. Мо танҳо либос меорем.', 'Every child is a <em>superhero.</em> We just bring the suits.')}</p>
    <p class="lead" style="color:rgba(255,255,255,.8)">{T('Наши актёры — не просто люди в костюмах. Это педагоги и аниматоры, которые знают, как увлечь и трёхлетнего малыша, и двенадцатилетнего «я уже взрослый».',
                                                          'Актёрони мо на танҳо одамон дар либос ҳастанд. Онҳо омӯзгорон ва аниматороне мебошанд, ки медонанд чӣ тавр ҳам кӯдаки сесола ва ҳам навраси дувоздаҳсолаи «ман аллакай калонам»-ро шавқманд кунанд.',
                                                          'Our actors aren’t just people in costumes. They’re educators and entertainers who know how to win over both a three-year-old and a twelve-year-old “I’m too old for this”.')}</p>
    <a class="btn white" href="about.html" style="margin-top:20px">{T('Узнать о нас', 'Дар бораи мо', 'About us')} {I['arrow']}</a>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="villain reveal">
      <img class="bg" src="{R_}assets/img/doom-army.jpg" alt="Doctor Doom">
      <span class="green-glow" style="left:28%;top:48%"></span>
      <span class="green-glow" style="left:62%;top:44%"></span>
      <div class="inner">
        <span class="eyebrow">{T('Новинка сезона', 'Навигарии мавсим', 'New this season')}</span>
        <h2 class="title">{T('Нужен злодей?', 'Бадкирдор лозим?', 'Need a villain?')}</h2>
        <p class="lead">{T('Доктор Дум похищает именинный торт, а дети вместе с героями проходят испытания, разгадывают шифры и спасают праздник. Злодей всегда проигрывает — это наше главное правило.',
                          'Доктор Дум торти зодрӯзро медуздад, кӯдакон бошанд якҷоя бо қаҳрамонон аз санҷишҳо мегузаранд, рамзҳоро мекушоянд ва ҷашнро наҷот медиҳанд. Бадкирдор ҳамеша мағлуб мешавад — ин қоидаи асосии мост.',
                          'Doctor Doom steals the birthday cake, and the kids team up with the heroes to beat challenges, crack codes and save the party. The villain always loses — that’s our number one rule.')}</p>
        <a class="btn" href="services.html" style="--b:#3a8f1f;margin-top:16px">{T('Квест со злодеем', 'Квест бо бадкирдор', 'Villain quest')} {I['arrow']}</a>
      </div>
    </div>
  </div>
</section>

<section class="section" style="padding-top:0">
  <div class="container">
    <div class="cta reveal">
      <div class="cta-text">
        <span class="eyebrow" style="color:#fff">{T('Свободные даты разбирают быстро', 'Санаҳои холӣ зуд банд мешаванд', 'Free dates go fast')}</span>
        <h2 class="title">{T('Мстители, <br>общий сбор!', 'Интиқомгирандагон, <br>ҷамъ шавед!', 'Avengers, <br>assemble!')}</h2>
        <p class="lead" style="color:rgba(255,255,255,.85)">{T('Оставьте заявку сегодня — и получите аквагрим героев в подарок.', 'Имрӯз дархост гузоред — ва аквагрими қаҳрамононро тӯҳфа гиред.', 'Book today and get hero face paint as a gift.')}</p>
        <div class="hero-actions"><a class="btn white" href="contacts.html#book">{T('Забронировать дату', 'Санаро банд кунед', 'Book a date')}</a><a class="btn ghost" href="services.html#calc">{T('Рассчитать цену', 'Ҳисоби нарх', 'Get a price')}</a></div>
      </div>
      <img src="{R_}assets/img/wolverine.png" alt="Wolverine">
    </div>
  </div>
</section>
""" + foot()


# ======================= ГЕРОИ =======================
def p_heroes():
    return head(T("Герои — Hero Squad", "Қаҳрамонон — Hero Squad", "Heroes — Hero Squad"),
                T("Каталог героев и злодеев для детского праздника.", "Феҳристи қаҳрамонон ва бадкирдорон барои ҷашни кӯдакона.", "Heroes and villains for your kids’ party."),
                "heroes", "heroes.html", page_no="02") + page_hero(
        T("8 героев · 3 злодейских сценария", "8 қаҳрамон · 3 сенарияи бадкирдор", "8 heroes · 3 villain scripts"),
        T('Наша <span class="red">команда</span>', 'Дастаи <span class="red">мо</span>', 'Our <span class="red">team</span>'),
        T("Переверните карточку, чтобы увидеть характеристики героя: силу, юмор и самое важное — любовь детей.",
          "Кортро гардонед, то хусусиятҳои қаҳрамонро бинед: қувва, ҳазл ва аз ҳама муҳим — меҳри кӯдакон.",
          "Flip a card to see the hero’s stats: strength, humour and, most importantly, kids’ love."),
        "panther.png", "radial-gradient(circle at 75% 40%,#6b2bd6 0,#2a0f5c 35%,#07070b 75%)", T("Герои", "Қаҳрамонон", "Heroes"), "Wakanda · Avengers · X-Men") + f"""
<section class="section" style="padding-top:40px">
  <div class="container">
    <div class="filters reveal">
      <button class="on" data-f="all">{T('Все', 'Ҳама', 'All')}</button>
      <button data-f="hero">{T('Герои', 'Қаҳрамонон', 'Heroes')}</button>
      <button data-f="anti">{T('Антигерои', 'Зидди қаҳрамонон', 'Antiheroes')}</button>
      <button data-f="villain">{T('Злодеи', 'Бадкирдорон', 'Villains')}</button>
    </div>
    <div class="heroes-row" id="heroes-grid"></div>
  </div>
</section>

<section class="section" style="padding-top:0">
  <div class="container">
    <div class="glass reveal" style="padding:50px;display:grid;grid-template-columns:1fr auto;gap:30px;align-items:center">
      <div>
        <span class="eyebrow">{T('Не нашли своего героя?', 'Қаҳрамони худро наёфтед?', 'Didn’t find your hero?')}</span>
        <h2 class="title" style="font-size:clamp(30px,4vw,52px)">{T('Сошьём костюм под заказ', 'Либосро бо фармоиш медӯзем', 'We’ll make a custom suit')}</h2>
        <p class="lead">{T('Капитан, Тор, Халк, Человек-муравей — расскажите, кого ждёт ребёнок, и мы подготовим героя за 3 недели.',
                          'Капитан, Тор, Халк, Одам-мӯрча — бигӯед, кӯдак киро интизор аст, мо қаҳрамонро дар 3 ҳафта омода мекунем.',
                          'Captain, Thor, Hulk, Ant-Man — tell us who your child is waiting for and we’ll have the hero ready in 3 weeks.')}</p>
      </div>
      <a class="btn" href="contacts.html#book">{T('Заказать героя', 'Фармоиши қаҳрамон', 'Order a hero')}</a>
    </div>
  </div>
</section>
""" + foot()


# ======================= УСЛУГИ =======================
def svc(n, icon, title, text, tags):
    return f"""<article class="svc reveal"><span class="num">0{n}</span><span class="ico">{I[icon]}</span><h3>{title}</h3><p>{text}</p><ul>{''.join(f'<li>{t}</li>' for t in tags)}</ul></article>"""


def pack(cls, name, sub, price, items, btn_cls, badge=""):
    b = f'<span class="badge">{badge}</span>' if badge else ""
    cur = T("смн", "смн", "TJS")
    return f"""<div class="pack {cls} reveal">{b}<h3>{name}</h3><span class="sub">{sub}</span><div class="amount">{price} <small>{cur}</small></div>
        <ul>{''.join(f'<li>{i}</li>' for i in items)}</ul><a class="btn {btn_cls}" href="contacts.html#book">{T('Выбрать', 'Интихоб', 'Choose')}</a></div>"""


def p_services():
    return head(T("Услуги и цены — Hero Squad", "Хизматҳо ва нархҳо — Hero Squad", "Services & prices — Hero Squad"),
                T("Программы праздников, пакеты и калькулятор стоимости.", "Барномаҳои ҷашн, бастаҳо ва ҳисобкунаки нарх.", "Party programmes, packages and a price calculator."),
                "services", "services.html", page_no="03") + page_hero(
        T("Цены в сомони · выезд по городу бесплатно", "Нархҳо бо сомонӣ · рафтан дар шаҳр ройгон", "Prices in TJS · free travel within the city"),
        T('Услуги <span class="red">&amp;</span> цены', 'Хизматҳо <span class="red">&amp;</span> нархҳо', 'Services <span class="red">&amp;</span> prices'),
        T("Шесть программ, три готовых пакета и калькулятор, в котором можно собрать свой идеальный праздник.",
          "Шаш барнома, се бастаи тайёр ва ҳисобкунак, ки дар он ҷашни беҳтарини худро сохта метавонед.",
          "Six programmes, three ready-made packages and a calculator to build your perfect party."),
        "widow.png", "linear-gradient(115deg,#0a1a6b 0 48%,#a10d13 48% 100%)", T("Услуги", "Хизматҳо", "Services"), T("Сценарии · пакеты · расчёт", "Сенарияҳо · бастаҳо · ҳисоб", "Scripts · packages · pricing")) + f"""
<section class="section" style="padding-top:40px">
  <div class="container">
    <div class="section-head reveal"><span class="eyebrow">{T('Программы', 'Барномаҳо', 'Programmes')}</span><h2 class="title">{T('Что мы <span class="red">устраиваем</span>', 'Мо чӣ <span class="red">ташкил мекунем</span>', 'What we <span class="red">do</span>')}</h2></div>
    <div class="services">
      {svc(1, 'cake', T('День рождения', 'Зодрӯз', 'Birthday party'), T('Герой поздравляет именинника, проводит игры и конкурсы, вручает медаль «Почётный Мститель».', 'Қаҳрамон соҳиби ҷашнро табрик мекунад, бозиҳо ва мусобиқаҳо мегузаронад ва медали «Интиқомгирандаи фахрӣ» медиҳад.', 'The hero greets the birthday child, runs games and contests, and awards the “Honorary Avenger” medal.'), [T('1–3 часа', '1–3 соат', '1–3 hours'), T('3–12 лет', '3–12 сола', 'ages 3–12'), T('дом / кафе', 'хона / қаҳвахона', 'home / café')])}
      {svc(2, 'map', T('Квест со злодеем', 'Квест бо бадкирдор', 'Villain quest'), T('Доктор Дум похищает торт. Шифры, ловушки, командные испытания и победа добра в финале.', 'Доктор Дум тортро медуздад. Рамзҳо, домҳо, санҷишҳои дастаҷамъӣ ва дар охир ғалабаи некӣ.', 'Doctor Doom steals the cake. Codes, traps, team challenges and good wins in the end.'), [T('от 6 лет', 'аз 6 сола', 'ages 6+'), T('до 30 детей', 'то 30 кӯдак', 'up to 30 kids'), T('сценарий под вас', 'сенария барои шумо', 'custom script')])}
      {svc(3, 'school', T('Академия героев', 'Академияи қаҳрамонон', 'Hero Academy'), T('Мини-школа супергероев: тренировка ловкости, научные опыты Старка и экзамен с дипломом.', 'Мактаби хурди суперқаҳрамонон: машқи чолокӣ, таҷрибаҳои илмии Старк ва имтиҳон бо диплом.', 'A mini superhero school: agility training, Stark’s science experiments and a diploma exam.'), [T('садики', 'боғчаҳо', 'kindergartens'), T('школы', 'мактабҳо', 'schools'), T('лагеря', 'лагерҳо', 'camps')])}
      {svc(4, 'star', T('Выпускной', 'Ҷашни хатм', 'Graduation'), T('Мстители поздравляют выпускников садика или начальной школы — с шоу и вручением дипломов.', 'Интиқомгирандагон хатмкунандагони боғча ё синфҳои ибтидоиро бо намоиш ва супоридани диплом табрик мекунанд.', 'The Avengers celebrate kindergarten or primary school graduates — with a show and diplomas.'), [T('группы', 'гурӯҳҳо', 'groups'), T('до 60 детей', 'то 60 кӯдак', 'up to 60 kids'), T('сцена', 'саҳна', 'stage')])}
      {svc(5, 'camera', T('Фотосессия с героем', 'Аксбардорӣ бо қаҳрамон', 'Hero photo shoot'), T('Постановочные кадры в образах, реквизит, щиты и маски. Готовые фото — через 3 дня.', 'Аксҳои саҳнавӣ дар образҳо, реквизит, сипарҳо ва ниқобҳо. Аксҳои тайёр — пас аз 3 рӯз.', 'Staged shots in character, props, shields and masks. Photos ready in 3 days.'), [T('30–60 минут', '30–60 дақиқа', '30–60 min'), T('фотограф', 'суратгир', 'photographer'), T('ретушь', 'ретуш', 'retouching')])}
      {svc(6, 'sparkle', T('Шоу-программа', 'Барномаи намоишӣ', 'Show programme'), T('Шоу мыльных пузырей, научное шоу с дымом, бумажное шоу и конфетти-пушки для финала.', 'Намоиши кафкҳои собун, намоиши илмӣ бо дуд, намоиши қоғазӣ ва тӯпҳои конфетти барои анҷом.', 'Bubble show, smoke science show, paper show and confetti cannons for the finale.'), [T('20–40 минут', '20–40 дақиқа', '20–40 min'), T('любой возраст', 'ҳар синну сол', 'all ages'), T('вау-эффект', 'вау-эффект', 'wow effect')])}
    </div>
  </div>
</section>

<section class="section" style="padding-top:20px">
  <div class="container">
    <div class="section-head center reveal"><span class="eyebrow">{T('Готовые пакеты', 'Бастаҳои тайёр', 'Packages')}</span><h2 class="title">{T('Выберите <span class="outline">уровень</span>', 'Сатҳро <span class="outline">интихоб кунед</span>', 'Choose your <span class="outline">level</span>')}</h2></div>
    <div class="packs">
      {pack('', T('Новичок', 'Навкор', 'Rookie'), T('Для небольшого домашнего праздника', 'Барои ҷашни хурди хонагӣ', 'For a small party at home'), '890',
            [T('1 герой на выбор', '1 қаҳрамон бо интихоб', '1 hero of your choice'), T('1,5 часа программы', '1,5 соат барнома', '1.5-hour programme'), T('Игры и конкурсы', 'Бозиҳо ва мусобиқаҳо', 'Games and contests'), T('Медаль имениннику', 'Медал барои соҳиби ҷашн', 'Medal for the birthday child')], 'ghost')}
      {pack('hot', T('Мститель', 'Интиқомгиранда', 'Avenger'), T('Самый популярный выбор родителей', 'Интихоби маъмултарини волидон', 'Parents’ favourite choice'), T('1 990', '1 990', '1,990'),
            [T('2 героя на выбор', '2 қаҳрамон бо интихоб', '2 heroes of your choice'), T('2 часа программы', '2 соат барнома', '2-hour programme'), T('Квест + шоу пузырей', 'Квест + намоиши кафкҳо', 'Quest + bubble show'), T('Аквагрим героев', 'Аквагрими қаҳрамонон', 'Hero face paint'), T('Медали всем гостям', 'Медал ба ҳамаи меҳмонон', 'Medals for every guest')], 'white', T('Хит сезона', 'Хити мавсим', 'Best seller'))}
      {pack('', T('Вселенная', 'Олам', 'Universe'), T('Когда праздник должен быть легендарным', 'Вақте ки ҷашн бояд афсонавӣ бошад', 'When the party must be legendary'), T('3 900', '3 900', '3,900'),
            [T('3 героя + злодей', '3 қаҳрамон + бадкирдор', '3 heroes + a villain'), T('3 часа программы', '3 соат барнома', '3-hour programme'), T('Квест «Похищение торта»', 'Квести «Дуздии торт»', '“The Stolen Cake” quest'), T('Фотограф и оформление', 'Суратгир ва ороиш', 'Photographer and decor'), T('Конфетти-финал', 'Анҷоми конфеттӣ', 'Confetti finale')], 'ghost')}
    </div>
  </div>
</section>

<section class="section" id="calc" style="padding-top:20px">
  <div class="container">
    <div class="section-head reveal"><span class="eyebrow">{T('Калькулятор', 'Ҳисобкунак', 'Calculator')}</span><h2 class="title">{T('Соберите <span class="red">свой</span> праздник', 'Ҷашни <span class="red">худро</span> созед', 'Build <span class="red">your</span> party')}</h2><p class="lead">{T('Отметьте героев, длительность и дополнения — цена посчитается сразу.', 'Қаҳрамонон, давомнокӣ ва иловаҳоро қайд кунед — нарх фавран ҳисоб мешавад.', 'Pick heroes, duration and extras — the price updates instantly.')}</p></div>
    <form class="calc" id="calc-form" onsubmit="return false">
      <div class="glass calc-box reveal">
        <div class="calc-group"><h3>1 · {T('Герои', 'Қаҳрамонон', 'Heroes')}</h3><div class="pick-grid" id="pick-heroes"></div></div>
        <div class="calc-group"><h3>2 · {T('Длительность', 'Давомнокӣ', 'Duration')}</h3><div class="range-row"><input type="range" id="hours" min="1" max="4" step="0.5" value="2" aria-label="hours"><output id="hours-out">2</output></div></div>
        <div class="calc-group"><h3>3 · {T('Количество детей', 'Шумораи кӯдакон', 'Number of kids')}</h3><div class="range-row"><input type="range" id="kids" min="5" max="40" value="12" aria-label="kids"><output id="kids-out">12</output></div><p style="color:var(--muted);font-size:13px;margin:8px 0 0">{T('До 10 детей — без доплаты, далее +15 смн за каждого.', 'То 10 кӯдак — бе пардохти иловагӣ, баъд барои ҳар кас +15 смн.', 'Up to 10 kids included, then +15 TJS each.')}</p></div>
        <div class="calc-group"><h3>4 · {T('Дополнения', 'Иловаҳо', 'Extras')}</h3><div class="chips" id="pick-extras"></div></div>
      </div>
      <aside class="summary reveal" data-d="1">
        <h3>{T('Ваш праздник', 'Ҷашни шумо', 'Your party')}</h3>
        <div id="sum-lines"></div>
        <div class="total" id="sum-total">0</div>
        <p class="note">{T('Выезд по городу — бесплатно. Итог подтверждает менеджер.', 'Рафтан дар дохили шаҳр ройгон. Ҳисоби ниҳоиро менеҷер тасдиқ мекунад.', 'Free travel within the city. A manager confirms the final price.')}</p>
        <div class="promo"><input id="promo" placeholder="{T('Промокод', 'Промокод', 'Promo code')}" aria-label="promo"><button type="button" id="promo-btn">OK</button></div>
        <div class="promo-msg"></div>
        <button type="button" class="btn white" id="to-book">{T('Оформить заявку', 'Дархост фиристодан', 'Send request')} {I['arrow']}</button>
      </aside>
    </form>
  </div>
</section>
""" + foot()


# ======================= О НАС =======================
def p_about():
    R_ = R()
    tl = [("2021", T("Первый костюм", "Либоси аввал", "The first suit"), T("Человек-паук на дне рождения брата. 20 детей, 3 часа, 0 сил к вечеру.", "Одам-тортанак дар зодрӯзи бародар. 20 кӯдак, 3 соат, бегоҳ 0 қувва.", "Spider-Man at a little brother’s birthday. 20 kids, 3 hours, 0 energy left.")),
          ("2022", T("Команда собирается", "Даста ҷамъ мешавад", "The team assembles"), T("Появились Железный человек и Чёрная Вдова. Первые 100 праздников.", "Одами оҳанин ва Бевазани Сиёҳ пайдо шуданд. 100 ҷашни аввал.", "Iron Man and Black Widow joined. The first 100 parties.")),
          ("2023", T("Злодеи в деле", "Бадкирдорон ба кор", "Villains join in"), T("Запустили квест с Доктором Думом — теперь это самая популярная программа.", "Квест бо Доктор Думро оғоз кардем — ҳоло ин барномаи маъмултарин аст.", "We launched the Doctor Doom quest — now our most popular programme.")),
          ("2024", T("Душанбе", "Душанбе", "Dushanbe"), T("Открыли второй город и «Академию героев» для садиков и школ.", "Шаҳри дуюм ва «Академияи қаҳрамонон»-ро барои боғчаҳо ва мактабҳо кушодем.", "Opened a second city and the Hero Academy for kindergartens and schools.")),
          ("2026", T("1 240+ праздников", "1 240+ ҷашн", "1,240+ parties"), T("8 героев, 14 актёров и этот сайт. Следующая цель — своя студия.", "8 қаҳрамон, 14 актёр ва ин сайт. Ҳадафи навбатӣ — студияи худ.", "8 heroes, 14 actors and this website. Next goal: our own studio."))]
    tl_html = "".join(f'<div class="tl-item reveal"><div class="yr">{y}</div><h3>{h}</h3><p>{p}</p></div>' for y, h, p in tl)
    return head(T("О нас — Hero Squad", "Дар бораи мо — Hero Squad", "About — Hero Squad"),
                T("История команды Hero Squad и наши правила.", "Таърихи дастаи Hero Squad ва қоидаҳои мо.", "The Hero Squad story and our rules."),
                "about", "about.html", page_no="04") + page_hero(
        T("С 2021 года · Худжанд", "Аз соли 2021 · Хуҷанд", "Since 2021 · Khujand"),
        T('О <span class="red">нас</span>', 'Дар бораи <span class="red">мо</span>', 'About <span class="red">us</span>'),
        T("Мы начинали с одного самодельного костюма Человека-паука. Сегодня — команда из 14 актёров и 8 героев.",
          "Мо бо як либоси худдӯхти Одам-тортанак оғоз кардем. Имрӯз — дастаи 14 актёр ва 8 қаҳрамон.",
          "We started with one home-made Spider-Man suit. Today we’re a team of 14 actors and 8 heroes."),
        "wolverine.png", "radial-gradient(circle at 78% 40%,#d6a50a 0,#5a4306 30%,#07070b 72%)", T("О нас", "Дар бораи мо", "About"), "Origin story") + f"""
<section class="section">
  <div class="container split">
    <div class="img-stack reveal">
      <div class="a"><img src="{R_}assets/img/ironman.jpg" alt="Iron Man" style="object-position:50% 20%"></div>
      <div class="b"><img src="{R_}assets/img/panther.png" alt="Black Panther"></div>
      <div class="badge-round"><span><b>5</b>{T('лет<br>подвигов', 'сол<br>корнамоӣ', 'years of<br>heroics')}</span></div>
    </div>
    <div class="reveal" data-d="1">
      <span class="eyebrow">{T('Наша история', 'Таърихи мо', 'Our story')}</span>
      <h2 class="title">{T('Из студенческого <span class="red">хобби</span> — в команду героев', 'Аз <span class="red">машғулияти</span> донишҷӯӣ — то дастаи қаҳрамонон', 'From a student <span class="red">hobby</span> to a team of heroes')}</h2>
      <p class="lead">{T('Всё началось с дня рождения младшего брата: костюм, сшитый за ночь, и двадцать детей, которые не отпускали «паука» три часа подряд.',
                         'Ҳама чиз аз зодрӯзи бародари хурдӣ оғоз ёфт: либосе, ки дар як шаб дӯхта шуд, ва бист кӯдак, ки «тортанак»-ро се соат пайиҳам раҳо намекарданд.',
                         'It all began at a little brother’s birthday: a suit sewn overnight and twenty kids who wouldn’t let “Spidey” go for three hours straight.')}</p>
      <p style="color:var(--muted)">{T('Сейчас в Hero Squad работают актёры, педагоги и аниматоры. Каждый проходит обучение: сценическое движение, работа с детьми разного возраста, безопасность и первая помощь. Костюмы мы заказываем у мастеров косплея и обновляем каждый сезон.',
                                      'Ҳоло дар Hero Squad актёрон, омӯзгорон ва аниматорон кор мекунанд. Ҳар кас омӯзиш мегузарад: ҳаракати саҳнавӣ, кор бо кӯдакони синну соли гуногун, бехатарӣ ва ёрии аввалин. Либосҳоро аз устоҳои косплей фармоиш медиҳем ва ҳар мавсим нав мекунем.',
                                      'Hero Squad is made up of actors, educators and entertainers. Everyone is trained in stage movement, working with kids of all ages, safety and first aid. Our suits are made by cosplay craftsmen and refreshed every season.')}</p>
      <div class="hero-actions"><a class="btn" href="heroes.html">{T('Познакомиться с героями', 'Шиносоӣ бо қаҳрамонон', 'Meet the heroes')}</a></div>
    </div>
  </div>
</section>

<section class="section" style="padding-top:0">
  <div class="container">
    <div class="section-head center reveal"><span class="eyebrow">{T('Кодекс героя', 'Кодекси қаҳрамон', 'Hero code')}</span><h2 class="title">{T('Три <span class="red">правила</span>', 'Се <span class="red">қоида</span>', 'Three <span class="red">rules</span>')}</h2></div>
    <div class="values">
      <div class="value reveal"><span class="dot"></span><h3>{T('Безопасность прежде всего', 'Бехатарӣ пеш аз ҳама', 'Safety first')}</h3><p>{T('Мягкий реквизит, проверенные площадки, актёры с медкнижками и курсом первой помощи.', 'Реквизити нарм, майдонҳои санҷидашуда, актёрон бо дафтарчаи тиббӣ ва курси ёрии аввалин.', 'Soft props, checked venues, actors with health certificates and first-aid training.')}</p><span class="big">01</span></div>
      <div class="value reveal" data-d="1"><span class="dot"></span><h3>{T('Герой не выходит из роли', 'Қаҳрамон аз нақш берун намеравад', 'The hero never breaks character')}</h3><p>{T('Для ребёнка это настоящий Человек-паук. Никаких «снимаю маску на минутку».', 'Барои кӯдак ин Одам-тортанаки ҳақиқӣ аст. Ҳеҷ «як дақиқа ниқобро мекашам».', 'To a child, this is the real Spider-Man. No “taking the mask off for a sec”.')}</p><span class="big">02</span></div>
      <div class="value reveal" data-d="2"><span class="dot"></span><h3>{T('Злодей всегда проигрывает', 'Бадкирдор ҳамеша мағлуб мешавад', 'The villain always loses')}</h3><p>{T('Даже Доктор Дум. Особенно Доктор Дум. Добро побеждает на каждом празднике.', 'Ҳатто Доктор Дум. Махсусан Доктор Дум. Дар ҳар ҷашн некӣ ғолиб меояд.', 'Even Doctor Doom. Especially Doctor Doom. Good wins at every party.')}</p><span class="big">03</span></div>
    </div>
  </div>
</section>

<section class="section" style="padding-top:20px">
  <div class="container">
    <div class="glass strange-box reveal">
      <div class="figwrap">
        <span class="mandala"></span>
        <div style="position:relative;height:100%;width:fit-content;margin:0 auto">
          <img src="{R_}assets/img/strange.png" alt="Doctor Strange">
          <button class="agamotto" style="left:calc(48% - 17px);top:calc(20.5% - 17px)" aria-label="Agamotto"></button>
        </div>
      </div>
      <div>
        <span class="eyebrow" style="color:#ffb347">{T('Доктор Стрэндж просчитал', 'Доктор Стрэндж ҳисоб кард', 'Doctor Strange calculated')}</span>
        <div class="big-num">14 000 605</div>
        <h2 class="title" style="font-size:clamp(28px,3.6vw,46px)">{T('вариантов праздника', 'варианти ҷашн', 'possible parties')}</h2>
        <p class="lead">{T('…и только в одном из них ребёнку было скучно. В том, где не позвали нас. Мы планируем каждый праздник заранее: сценарий под возраст, запасные игры на случай дождя и план «Б», если торт всё-таки похитят по-настоящему.',
                          '…ва танҳо дар яке аз онҳо кӯдак дилгир шуд. Дар ҳамон, ки моро даъват накарданд. Мо ҳар ҷашнро пешакӣ ба нақша мегирем: сенария мувофиқи синну сол, бозиҳои эҳтиётӣ барои ҳавои боронӣ ва нақшаи «Б», агар тортро воқеан дузданд.',
                          '…and the child was bored in only one of them. The one where we weren’t invited. We plan every party in advance: an age-appropriate script, backup games for rainy days and a plan B in case the cake really does get stolen.')}</p>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="section-head center reveal"><span class="eyebrow">{T('Хронология', 'Солнома', 'Timeline')}</span><h2 class="title">{T('Наша <span class="outline">мультивселенная</span>', 'Мултиоламаи <span class="outline">мо</span>', 'Our <span class="outline">multiverse</span>')}</h2></div>
    <div class="timeline">{tl_html}</div>
  </div>
</section>

<section class="section" style="padding-top:0">
  <div class="container">
    <div class="stats reveal">
      <div class="stat"><b><span data-count="14">0</span></b><span>{T('актёров', 'актёр', 'actors')}</span></div>
      <div class="stat"><b><span data-count="2">0</span></b><span>{T('города', 'шаҳр', 'cities')}</span></div>
      <div class="stat"><b><span data-count="37">0</span></b><span>{T('сценариев', 'сенария', 'scripts')}</span></div>
      <div class="stat"><b><span data-count="0">0</span></b><span>{T('побед злодеев', 'ғалабаи бадкирдорон', 'villain wins')}</span></div>
    </div>
  </div>
</section>
""" + foot()


# ======================= КОНТАКТЫ =======================
def ccard(icon, label, val, href="#"):
    return f'<a class="c-card reveal" href="{href}"><span class="ico">{I[icon]}</span><span><small>{label}</small><b>{val}</b></span></a>'


def p_contacts():
    faq = [
        (T("За сколько дней нужно бронировать?", "Чанд рӯз пеш бояд фармоиш дод?", "How far ahead should I book?"),
         T("Лучше за 1–2 недели, в выходные — за 3. Но если дата свободна, приедем и завтра.", "Беҳтар 1–2 ҳафта пеш, барои рӯзҳои истироҳат — 3 ҳафта. Аммо агар сана холӣ бошад, фардо ҳам меоем.", "Ideally 1–2 weeks ahead, 3 for weekends. But if the date is free, we can come tomorrow.")),
        (T("Сколько детей может быть на празднике?", "Дар ҷашн чанд кӯдак буда метавонад?", "How many kids can attend?"),
         T("Один герой комфортно работает с группой до 15 детей. Для больших компаний советуем двух героев.", "Як қаҳрамон бо гурӯҳи то 15 кӯдак бароҳат кор мекунад. Барои гурӯҳҳои калон ду қаҳрамонро тавсия медиҳем.", "One hero works comfortably with up to 15 kids. For bigger groups we recommend two heroes.")),
        (T("Можно ли выбрать сценарий?", "Оё сенарияро интихоб кардан мумкин аст?", "Can I choose the script?"),
         T("Конечно. Расскажите об интересах ребёнка — подстроим игры, квест и музыку.", "Албатта. Дар бораи шавқу ҳаваси кӯдак гӯед — бозиҳо, квест ва мусиқиро мувофиқ мекунем.", "Of course. Tell us what your child loves and we’ll tailor the games, quest and music.")),
        (T("Герои снимают маски?", "Қаҳрамонон ниқобро мекашанд?", "Do the heroes take off their masks?"),
         T("Нет. Для детей это настоящие супергерои, и мы бережём эту магию до конца праздника.", "Не. Барои кӯдакон онҳо суперқаҳрамонони ҳақиқӣ ҳастанд ва мо ин ҷодуро то охири ҷашн нигоҳ медорем.", "No. To the kids they’re real superheroes, and we keep the magic alive until the very end.")),
        (T("Как оплатить?", "Чӣ тавр пардохт кунам?", "How do I pay?"),
         T("Предоплата 30% при бронировании, остаток — после праздника. Наличными или переводом.", "Пешпардохт 30% ҳангоми фармоиш, боқимонда — пас аз ҷашн. Нақд ё бо интиқол.", "30% deposit when booking, the rest after the party. Cash or bank transfer.")),
        (T("А если на праздник придёт Танос?", "Агар Танос ба ҷашн ояд, чӣ?", "What if Thanos shows up?"),
         T("Не волнуйтесь — у нас есть план. И кое-что ещё", "Хавотир нашавед — мо нақша дорем. Ва боз чизе", "Don’t worry — we have a plan. And something else") + ' <button class="stone inline" data-stone="power" aria-label="?"></button>'),
    ]
    return head(T("Контакты — Hero Squad", "Тамос — Hero Squad", "Contacts — Hero Squad"),
                T("Свяжитесь с нами и забронируйте героя на праздник.", "Бо мо тамос гиред ва қаҳрамонро ба ҷашн фармоиш диҳед.", "Get in touch and book a hero for your party."),
                "contacts", "contacts.html", page_no="05") + page_hero(
        T("Ответим за 15 минут", "Дар 15 дақиқа ҷавоб медиҳем", "We reply within 15 minutes"),
        T('Связь с <span class="red">базой</span>', 'Тамос бо <span class="red">база</span>', 'Contact <span class="red">HQ</span>'),
        T("Оставьте заявку — дежурный герой перезвонит, уточнит детали и предложит сценарий.", "Дархост гузоред — қаҳрамони навбатдор занг зада, тафсилотро аниқ мекунад ва сенария пешниҳод менамояд.", "Leave a request — the hero on duty will call back, clarify details and suggest a script."),
        "doom.png", "radial-gradient(circle at 78% 40%,#2f7a22 0,#0e2a0a 34%,#07070b 72%)", T("Контакты", "Тамос", "Contacts"), "Hero Squad HQ") + f"""
<section class="section" id="book" style="padding-top:40px">
  <div class="container contact-grid">
    <div>
      <div class="c-cards">
        {ccard('phone', T('Телефон', 'Телефон', 'Phone'), '+992 92 777 00 00', 'tel:+992927770000')}
        {ccard('mail', T('Почта', 'Почта', 'Email'), 'hello@herosquad.tj', 'mailto:hello@herosquad.tj')}
        {ccard('pin', T('Где работаем', 'Дар куҷо кор мекунем', 'Where we work'), T('Худжанд · Душанбе', 'Хуҷанд · Душанбе', 'Khujand · Dushanbe'))}
        {ccard('clock', T('Режим работы', 'Вақти корӣ', 'Hours'), T('Ежедневно 9:00–21:00', 'Ҳар рӯз 9:00–21:00', 'Daily 9:00–21:00'))}
      </div>
      <div class="map-card reveal">
        <svg viewBox="0 0 600 260" preserveAspectRatio="xMidYMid slice" aria-hidden="true">
          <rect width="600" height="260" fill="#0d1020"/>
          <g stroke="#1b2140" stroke-width="10" fill="none"><path d="M0 60h600M0 150h600M0 220h600M80 0v260M210 0v260M360 0v260M500 0v260"/></g>
          <g stroke="#262e57" stroke-width="3" fill="none"><path d="M0 105h600M0 190h600M140 0v260M290 0v260M430 0v260"/></g>
          <path d="M-10 120C100 90 160 150 260 125S420 70 610 100" stroke="#1d3ed6" stroke-width="22" fill="none" opacity=".55"/>
          <text x="440" y="88" fill="#4d64d8" font-size="11" font-family="Oswald" letter-spacing="3">{T('СЫРДАРЬЯ', 'СИРДАРЁ', 'SYR DARYA')}</text>
          <rect x="380" y="160" width="60" height="40" rx="6" fill="#15301a"/>
        </svg>
        <div class="map-pin"><span></span></div>
        <div class="map-label">Hero Squad HQ · {T('выезд в любую точку города', 'ба ҳар нуқтаи шаҳр меоем', 'we come anywhere in the city')}</div>
      </div>
    </div>
    <form class="glass form reveal" id="book-form" novalidate data-d="1">
      <span class="eyebrow">{T('Заявка', 'Дархост', 'Request')}</span>
      <h3>{T('Забронировать героя', 'Фармоиши қаҳрамон', 'Book a hero')}</h3>
      <p style="color:var(--muted);margin:0">{T('Поля со звёздочкой обязательны.', 'Майдонҳои бо ситора ҳатмӣ мебошанд.', 'Fields marked * are required.')}</p>
      <div class="row">
        <div class="field"><input id="f-name" placeholder=" " autocomplete="name"><label for="f-name">{T('Ваше имя *', 'Номи шумо *', 'Your name *')}</label><div class="err-msg">{T('Как к вам обращаться?', 'Шуморо чӣ ном гирем?', 'What should we call you?')}</div></div>
        <div class="field"><input id="f-phone" placeholder=" " inputmode="tel" autocomplete="tel"><label for="f-phone">{T('Телефон *', 'Телефон *', 'Phone *')}</label><div class="err-msg">{T('Формат: +992 XX XXX XX XX', 'Формат: +992 XX XXX XX XX', 'Format: +992 XX XXX XX XX')}</div></div>
      </div>
      <div class="row">
        <div class="field"><input id="f-date" type="date" placeholder=" "><label for="f-date">{T('Дата праздника *', 'Санаи ҷашн *', 'Party date *')}</label><div class="err-msg">{T('Выберите дату', 'Санаро интихоб кунед', 'Pick a date')}</div></div>
        <div class="field"><select id="f-hero"></select><label for="f-hero">{T('Герой *', 'Қаҳрамон *', 'Hero *')}</label><div class="err-msg">{T('Кого позовём?', 'Киро даъват кунем?', 'Who should we send?')}</div></div>
      </div>
      <div class="field"><textarea id="f-msg" placeholder=" "></textarea><label for="f-msg">{T('Пожелания: возраст, место, количество гостей', 'Хоҳишҳо: синну сол, ҷой, шумораи меҳмонон', 'Notes: age, venue, number of guests')}</label></div>
      <button class="btn" type="submit">{T('Отправить сигнал', 'Сигнал фиристодан', 'Send the signal')} {I['arrow']}</button>
    </form>
  </div>
</section>

<section class="section" style="padding-top:20px">
  <div class="container">
    <div class="section-head center reveal"><span class="eyebrow">FAQ</span><h2 class="title">{T('Частые <span class="red">вопросы</span>', 'Саволҳои <span class="red">маъмул</span>', 'Common <span class="red">questions</span>')}</h2></div>
    <div class="faq">
      {''.join(f'<details class="reveal"><summary>{q}</summary><div class="ans">{a}</div></details>' for q, a in faq)}
    </div>
  </div>
</section>
""" + foot()


# ======================= 404 =======================
def p_404():
    return head(T("404 — ДУМ конфисковал страницу", "404 — ДУМ саҳифаро мусодира кард", "404 — DOOM confiscated this page"),
                "404", "lost", "404.html", page_no="??") + f"""
<section class="e404">
  <div class="bg"></div>
  <div>
    <span class="eyebrow" style="color:#9cff6b">{T('Ошибка мультивселенной', 'Хатои мултиолам', 'Multiverse error')}</span>
    <h1>404</h1>
    <p class="typed" aria-live="polite"></p>
    <div class="hero-actions" style="justify-content:center">
      <a class="btn" href="index.html">{T('Вернуться на Землю-616', 'Бозгашт ба Замин-616', 'Back to Earth-616')}</a>
      <a class="btn ghost" href="heroes.html">{T('К героям', 'Ба қаҳрамонон', 'To the heroes')}</a>
    </div>
  </div>
</section>
""" + foot()


PAGES = {"index.html": p_index, "heroes.html": p_heroes, "services.html": p_services,
         "about.html": p_about, "contacts.html": p_contacts, "404.html": p_404}

for code, (folder, _) in LANGS.items():
    L = code
    out = SITE / folder
    out.mkdir(parents=True, exist_ok=True)
    for name, fn in PAGES.items():
        (out / name).write_text(fn(), encoding="utf-8")
    print("built", code, out)
